// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFOVbeKPnzz-Bzt4tv8Pwv0blCwzAdlY',
    appId: '1:853570366597:web:9318c4a9ca4697b474cdec',
    messagingSenderId: '853570366597',
    projectId: 'vertx-b56bb',
    authDomain: 'vertx-b56bb.firebaseapp.com',
    storageBucket: 'vertx-b56bb.firebasestorage.app',
    measurementId: 'G-HJNMPTMNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrm8cxNJv2RchRsKG5rs2x2YWtLseVklo',
    appId: '1:853570366597:android:d4933ea94c8b471374cdec',
    messagingSenderId: '853570366597',
    projectId: 'vertx-b56bb',
    storageBucket: 'vertx-b56bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdBSTfdl4qVpgREws1qdn_N0LssCHkg6Y',
    appId: '1:853570366597:ios:3411d63a49c5635174cdec',
    messagingSenderId: '853570366597',
    projectId: 'vertx-b56bb',
    storageBucket: 'vertx-b56bb.firebasestorage.app',
    iosBundleId: 'com.vertxlearning.app',
  );
}
